# Generated by Django 5.1.4 on 2025-01-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
