# Generated by Django 5.1.4 on 2025-01-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_region_country_remove_subscription_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='added_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Subscription',
            new_name='subscription',
        ),
        migrations.AddField(
            model_name='payment',
            name='or_ref_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
