# Generated by Django 5.1.4 on 2025-01-10 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_address_remove_user_contact_no_and_more'),
        ('home', '0004_alter_barangay_name_alter_municipality_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='subscriber',
            new_name='subscription',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='subscriber',
            new_name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emps', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='accounts.subscriber'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='billed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee'),
        ),
    ]
