# Generated by Django 5.1.4 on 2025-01-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_modem_is_gigabit_modem_modem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='modem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
