# Generated by Django 5.1.4 on 2025-01-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_modem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
