# Generated by Django 5.1.4 on 2025-01-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_subscription_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='referred_by',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
