# Generated by Django 5.1.4 on 2025-01-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_subscription_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='referred_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
