# Generated by Django 5.1.4 on 2025-01-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_subscription_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber_name',
        ),
    ]
