# Generated by Django 5.1.4 on 2025-01-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_subscription_subscriber_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='alias',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
