# Generated by Django 5.1.4 on 2025-01-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_subscription_alias_subscription_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_suspended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_activated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_terminated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('warning', 'Warning'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_type',
            field=models.CharField(choices=[('government', 'Government'), ('vendo', 'Vendo'), ('residential', 'Residential'), ('business', 'Business'), ('vip', 'VIP'), ('test', 'Testing'), ('employee', 'Employee'), ('station', 'Station')], default='residential', max_length=50),
        ),
    ]
