# Generated by Django 5.1.4 on 2025-01-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_subscription_date_suspended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
