# Generated by Django 5.1.4 on 2025-01-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_subscription_purok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
