# Generated by Django 5.1.4 on 2025-01-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_subscription_sub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
