# Generated by Django 5.1.4 on 2025-01-15 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_subscription_sub_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.province'),
        ),
    ]
