# Generated by Django 5.1.4 on 2025-01-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_subscription_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='sub_code',
            new_name='account_no',
        ),
    ]
