# Generated by Django 5.1.4 on 2025-01-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_sub_code_subscription_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='account_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
