# Generated by Django 5.1.4 on 2025-01-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_subscription_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='account_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
