# Generated by Django 5.1.4 on 2025-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_subscription_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='account_no',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
