# Generated by Django 5.1.4 on 2025-01-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_subscription_account_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='account_no',
            new_name='no',
        ),
    ]
