# Generated by Django 5.1.4 on 2025-01-16 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_account_no_subscription_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billing',
            name='notice',
            field=models.CharField(choices=[('disconnection', 'Disconnection'), ('updated', 'Updated'), ('disconnected', 'Disconnected'), ('warning', 'Warning')], default='updated', max_length=50),
        ),
    ]
