# Generated by Django 5.1.4 on 2025-01-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_payment_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('gcash', 'GCash'), ('maya', 'Maya'), ('bank', 'Bank')], default='cash', max_length=10),
        ),
    ]
