# Generated by Django 5.1.4 on 2025-01-18 00:42

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=home.models.pay_picture_path),
        ),
    ]
