# Generated by Django 5.1.4 on 2025-01-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_payment_reference_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
