# Generated by Django 5.1.4 on 2025-01-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_ticket_prepared_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='created_on',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
