# Generated by Django 5.1.4 on 2025-01-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_issue_created_on_ticket_ticket_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
