# Generated by Django 5.1.4 on 2025-01-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_ticket_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
