# Generated by Django 5.1.4 on 2025-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_ticket_assigned_to_alter_ticket_prepared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sub_schedule',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End'), ('others', 'Others')], default='', max_length=20, null=True),
        ),
    ]
