# Generated by Django 5.1.4 on 2025-01-26 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_subscription_sub_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='sub_schedule',
        ),
        migrations.AddField(
            model_name='billing',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billing',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End'), ('others', 'Others')], default='start', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='billed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
