# Generated by Django 5.1.4 on 2025-01-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_subscription_sub_schedule_billing_collector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='bill_schedule',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End'), ('others', 'Others')], default='start', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_partial',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
