# Generated by Django 5.1.4 on 2025-01-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_subscription_bill_schedule_subscription_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['-billing_date']},
        ),
        migrations.AlterModelOptions(
            name='modem',
            options={'ordering': ['modem_brand']},
        ),
        migrations.AddField(
            model_name='billing',
            name='bill_schedule',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End'), ('others', 'Others')], default='start', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('net', 'Internet'), ('foc', 'FOC'), ('labor', 'labor'), ('others', 'Others')], default='net', max_length=10, null=True),
        ),
    ]
