# Generated by Django 5.1.4 on 2025-01-30 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_billing_options_alter_modem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='home.billing'),
        ),
    ]
