# Generated by Django 5.1.4 on 2025-02-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_payment_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('net', 'Internet'), ('foc', 'FOC'), ('labor', 'Labor'), ('others', 'Others')], default='net', max_length=10, null=True),
        ),
    ]
