# Generated by Django 5.1.4 on 2025-01-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
