# Generated by Django 5.1.4 on 2025-01-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ext_name',
            field=models.CharField(blank=True, choices=[('jr', 'Jr.'), ('sr', 'Sr.')], default='', max_length=10, null=True),
        ),
    ]
