# Generated by Django 5.1.4 on 2025-01-10 23:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_address_remove_user_contact_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_code',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=accounts.models.emp_picture_path),
        ),
    ]
