# Generated by Django 5.1.4 on 2025-01-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_employee_ext_name_remove_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('employee', 'Employee')], default='', max_length=20, null=True),
        ),
    ]
