# Generated by Django 5.1.4 on 2025-01-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_subscriber_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='contact_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
