# Generated by Django 5.1.4 on 2025-01-13 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_subscriber_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
