# Generated by Django 5.1.4 on 2025-01-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_subscriber_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='id_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
