# Generated by Django 5.1.4 on 2025-01-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_subscriber_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='id_no',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
