# Generated by Django 5.1.4 on 2025-01-18 00:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_subscriber_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=accounts.models.subs_picture_path),
        ),
    ]
